# https://cloud.google.com/appengine/docs/standard/python/config/appref
runtime: go115
main: web

instance_class: F1

env_variables:
  IOTCORE_REGISTRY: 'TODO'
  PUBSUB_VERIFICATION_TOKEN: 'TODO'
  PUBSUB_AUDIENCE: 'TODO'
  INFLUXDB_SERVER: 'TODO'
  INFLUXDB_TOKEN: 'TODO'
  INFLUXDB_ORG: 'TODO'
  INFLUXDB_BUCKET: 'TODO'

handlers:
- url: /static
  static_dir: web/static
  secure: always
- url: /.*
  script: auto
  secure: always
