# https://cloud.google.com/appengine/docs/standard/python/config/appref
runtime: go111
main: web

instance_class: F2

env_variables:
  IOTCORE_REGISTRY: 'TODO'

handlers:
- url: /static
  static_dir: web/static
  secure: always
- url: /_ah/push-handlers/.*
  script: auto
  login: admin
  secure: always
- url: /uploadz
  script: auto
  secure: always
  login: admin
- url: /.*
  script: auto
  secure: always
