// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: measurement.proto

package measurementpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Measurement struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	DeviceId  string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Temp      *wrapperspb.FloatValue `protobuf:"bytes,3,opt,name=temp,proto3" json:"temp,omitempty"`
	Pm25      *wrapperspb.FloatValue `protobuf:"bytes,5,opt,name=pm25,proto3" json:"pm25,omitempty"`
	Pm10      *wrapperspb.FloatValue `protobuf:"bytes,6,opt,name=pm10,proto3" json:"pm10,omitempty"`
	Rh        *wrapperspb.FloatValue `protobuf:"bytes,7,opt,name=rh,proto3" json:"rh,omitempty"`
	// This field should only be set when the measurement is not uploaded
	// immediately after it is taken, e.g. if the network goes down and
	// measurements are stored locally before upload is attempted again later.
	UploadTimestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=upload_timestamp,json=uploadTimestamp,proto3" json:"upload_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Measurement) Reset() {
	*x = Measurement{}
	mi := &file_measurement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Measurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Measurement) ProtoMessage() {}

func (x *Measurement) ProtoReflect() protoreflect.Message {
	mi := &file_measurement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Measurement.ProtoReflect.Descriptor instead.
func (*Measurement) Descriptor() ([]byte, []int) {
	return file_measurement_proto_rawDescGZIP(), []int{0}
}

func (x *Measurement) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Measurement) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Measurement) GetTemp() *wrapperspb.FloatValue {
	if x != nil {
		return x.Temp
	}
	return nil
}

func (x *Measurement) GetPm25() *wrapperspb.FloatValue {
	if x != nil {
		return x.Pm25
	}
	return nil
}

func (x *Measurement) GetPm10() *wrapperspb.FloatValue {
	if x != nil {
		return x.Pm10
	}
	return nil
}

func (x *Measurement) GetRh() *wrapperspb.FloatValue {
	if x != nil {
		return x.Rh
	}
	return nil
}

func (x *Measurement) GetUploadTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadTimestamp
	}
	return nil
}

type GetDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      []string               `protobuf:"bytes,1,rep,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevicesResponse) Reset() {
	*x = GetDevicesResponse{}
	mi := &file_measurement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesResponse) ProtoMessage() {}

func (x *GetDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_measurement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesResponse.ProtoReflect.Descriptor instead.
func (*GetDevicesResponse) Descriptor() ([]byte, []int) {
	return file_measurement_proto_rawDescGZIP(), []int{1}
}

func (x *GetDevicesResponse) GetDeviceId() []string {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

type GetLatestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestRequest) Reset() {
	*x = GetLatestRequest{}
	mi := &file_measurement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestRequest) ProtoMessage() {}

func (x *GetLatestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_measurement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestRequest.ProtoReflect.Descriptor instead.
func (*GetLatestRequest) Descriptor() ([]byte, []int) {
	return file_measurement_proto_rawDescGZIP(), []int{2}
}

func (x *GetLatestRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

var File_measurement_proto protoreflect.FileDescriptor

const file_measurement_proto_rawDesc = "" +
	"\n" +
	"\x11measurement.proto\x12\vmeasurement\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xeb\x02\n" +
	"\vMeasurement\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12/\n" +
	"\x04temp\x18\x03 \x01(\v2\x1b.google.protobuf.FloatValueR\x04temp\x12/\n" +
	"\x04pm25\x18\x05 \x01(\v2\x1b.google.protobuf.FloatValueR\x04pm25\x12/\n" +
	"\x04pm10\x18\x06 \x01(\v2\x1b.google.protobuf.FloatValueR\x04pm10\x12+\n" +
	"\x02rh\x18\a \x01(\v2\x1b.google.protobuf.FloatValueR\x02rh\x12E\n" +
	"\x10upload_timestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0fuploadTimestamp\"1\n" +
	"\x12GetDevicesResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x03(\tR\bdeviceId\"/\n" +
	"\x10GetLatestRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId2\xa5\x01\n" +
	"\x12MeasurementService\x12G\n" +
	"\n" +
	"GetDevices\x12\x16.google.protobuf.Empty\x1a\x1f.measurement.GetDevicesResponse\"\x00\x12F\n" +
	"\tGetLatest\x12\x1d.measurement.GetLatestRequest\x1a\x18.measurement.Measurement\"\x00B7Z5github.com/mtraver/environmental-sensor/measurementpbb\x06proto3"

var (
	file_measurement_proto_rawDescOnce sync.Once
	file_measurement_proto_rawDescData []byte
)

func file_measurement_proto_rawDescGZIP() []byte {
	file_measurement_proto_rawDescOnce.Do(func() {
		file_measurement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_measurement_proto_rawDesc), len(file_measurement_proto_rawDesc)))
	})
	return file_measurement_proto_rawDescData
}

var file_measurement_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_measurement_proto_goTypes = []any{
	(*Measurement)(nil),           // 0: measurement.Measurement
	(*GetDevicesResponse)(nil),    // 1: measurement.GetDevicesResponse
	(*GetLatestRequest)(nil),      // 2: measurement.GetLatestRequest
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*wrapperspb.FloatValue)(nil), // 4: google.protobuf.FloatValue
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_measurement_proto_depIdxs = []int32{
	3, // 0: measurement.Measurement.timestamp:type_name -> google.protobuf.Timestamp
	4, // 1: measurement.Measurement.temp:type_name -> google.protobuf.FloatValue
	4, // 2: measurement.Measurement.pm25:type_name -> google.protobuf.FloatValue
	4, // 3: measurement.Measurement.pm10:type_name -> google.protobuf.FloatValue
	4, // 4: measurement.Measurement.rh:type_name -> google.protobuf.FloatValue
	3, // 5: measurement.Measurement.upload_timestamp:type_name -> google.protobuf.Timestamp
	5, // 6: measurement.MeasurementService.GetDevices:input_type -> google.protobuf.Empty
	2, // 7: measurement.MeasurementService.GetLatest:input_type -> measurement.GetLatestRequest
	1, // 8: measurement.MeasurementService.GetDevices:output_type -> measurement.GetDevicesResponse
	0, // 9: measurement.MeasurementService.GetLatest:output_type -> measurement.Measurement
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_measurement_proto_init() }
func file_measurement_proto_init() {
	if File_measurement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_measurement_proto_rawDesc), len(file_measurement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_measurement_proto_goTypes,
		DependencyIndexes: file_measurement_proto_depIdxs,
		MessageInfos:      file_measurement_proto_msgTypes,
	}.Build()
	File_measurement_proto = out.File
	file_measurement_proto_goTypes = nil
	file_measurement_proto_depIdxs = nil
}
