package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	"github.com/mtraver/environmental-sensor/graph/model"
	"github.com/mtraver/environmental-sensor/measurement"
	"github.com/mtraver/environmental-sensor/web/device"
)

// Measurements is the resolver for the measurements field.
func (r *queryResolver) Measurements(ctx context.Context, startTime string, endTime *string) ([]*model.Measurement, error) {
	start, err := gqlTimestampToTime(startTime)
	if err != nil {
		return nil, err
	}

	var measurements map[string][]measurement.StorableMeasurement
	if endTime == nil {
		measurements, err = r.Database.Since(ctx, start)
	} else {
		end, err := gqlTimestampToTime(*endTime)
		if err != nil {
			return nil, err
		}

		measurements, err = r.Database.Between(ctx, start, end)
	}

	gqlMeasurements := []*model.Measurement{}
	for _, ms := range measurements {
		for _, m := range ms {
			m.FillDerivedMetrics()
			gqlMeasurements = append(gqlMeasurements, storableMeasurementToGQLMeasurement(m))
		}
	}

	return gqlMeasurements, nil
}

// Latest is the resolver for the latest field.
func (r *queryResolver) Latest(ctx context.Context) ([]*model.Measurement, error) {
	ids, err := device.GetDeviceIDsAWS(ctx, r.AWSRoleARN, r.AWSRegion)
	if err != nil {
		return nil, err
	}

	latest, err := r.Database.Latest(ctx, ids)
	if err != nil {
		return nil, err
	}

	gqlMeasurements := []*model.Measurement{}
	for _, m := range latest {
		m.FillDerivedMetrics()
		gqlMeasurements = append(gqlMeasurements, storableMeasurementToGQLMeasurement(m))
	}

	return gqlMeasurements, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
