// Code generated by "stringer -type ConnectionType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GCP-0]
	_ = x[AWS-1]
}

const _ConnectionType_name = "GCPAWS"

var _ConnectionType_index = [...]uint8{0, 3, 6}

func (i ConnectionType) String() string {
	if i < 0 || i >= ConnectionType(len(_ConnectionType_index)-1) {
		return "ConnectionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConnectionType_name[_ConnectionType_index[i]:_ConnectionType_index[i+1]]
}
