"""Publish to Google Cloud Pub/Sub"""
from google.cloud import pubsub_v1  # pylint: disable=import-error
from google.protobuf import timestamp_pb2  # pylint: disable=no-name-in-module

import loggers.base_logger

# Auto-generated by protobuf compiler
from loggers import measurement_pb2


class PubSubLogger(loggers.base_logger.Logger):
  """A logger that publishes to Google Cloud Pub/Sub."""

  def __init__(self, project_id, topic, device_id):
    """Creates a logger that publishes to Google Cloud Pub/Sub.

    Args:
      project_id: The cloud project ID this device belongs to.
      topic: The Cloud Pub/Sub topic name.
      device_id: Device ID string.
    """
    self._project_id = project_id
    self._topic = topic
    self._device_id = device_id

  def _get_proto(self, timestamp, values):
    timestamp_proto = timestamp_pb2.Timestamp()
    timestamp_proto.FromDatetime(timestamp)

    # Just one value can be stored, so take the mean of the given values.
    # TODO(mtraver) Allow user to configure this behavior?
    mean_temp = float(sum(values)) / len(values)

    return measurement_pb2.Measurement(
        device_id=self._device_id, timestamp=timestamp_proto, temp=mean_temp)

  def log(self, timestamp, values):
    publisher = pubsub_v1.PublisherClient()
    topic_path = publisher.topic_path(self._project_id, self._topic)

    publisher.publish(
        topic_path, self._get_proto(timestamp, values).SerializeToString())
