# https://cloud.google.com/appengine/docs/standard/python/config/appref
runtime: go
api_version: go1.9

env_variables:
  # Save data to Datastore
  DB_TYPE: 'datastore'

  # To save to Bigtable, comment out the DB_TYPE line above, uncomment the
  # lines below, and fill in the TODOs.
  # DB_TYPE: 'bigtable'
  # BIGTABLE_INSTANCE: 'TODO'
  # BIGTABLE_TABLE: 'TODO'

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
- url: /static
  static_dir: static
  secure: always
- url: /_ah/push-handlers/.*
  script: _go_app
  login: admin
  secure: always
- url: /.*
  script: _go_app
  login: admin
  secure: always
