# https://cloud.google.com/appengine/docs/standard/python/config/appref
runtime: go
api_version: go1.8

env_variables:
  # To save to Datastore, uncomment the line below
  # DB_TYPE: 'datastore'

  # To save to Bigtable, uncomment the lines below and fill in the TODOs
  # DB_TYPE: 'bigtable'
  # BIGTABLE_INSTANCE: 'TODO'
  # BIGTABLE_TABLE: 'TODO'

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /_ah/push-handlers/.*
  script: _go_app
  login: admin
  secure: always
- url: /.*
  script: _go_app
  login: admin
  secure: always
