// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Measurement struct {
	DeviceID        string   `json:"deviceId"`
	Timestamp       string   `json:"timestamp"`
	UploadTimestamp string   `json:"uploadTimestamp"`
	Temp            *float64 `json:"temp,omitempty"`
	Pm25            *float64 `json:"pm25,omitempty"`
	Pm10            *float64 `json:"pm10,omitempty"`
	Rh              *float64 `json:"rh,omitempty"`
	Aqi             *float64 `json:"aqi,omitempty"`
}

type Query struct {
}
