// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: configpb/config.proto

package configpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Job_Operation int32

const (
	Job_INVALID  Job_Operation = 0
	Job_SETUP    Job_Operation = 1
	Job_SENSE    Job_Operation = 2
	Job_SHUTDOWN Job_Operation = 3
)

// Enum value maps for Job_Operation.
var (
	Job_Operation_name = map[int32]string{
		0: "INVALID",
		1: "SETUP",
		2: "SENSE",
		3: "SHUTDOWN",
	}
	Job_Operation_value = map[string]int32{
		"INVALID":  0,
		"SETUP":    1,
		"SENSE":    2,
		"SHUTDOWN": 3,
	}
)

func (x Job_Operation) Enum() *Job_Operation {
	p := new(Job_Operation)
	*p = x
	return p
}

func (x Job_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Job_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_configpb_config_proto_enumTypes[0].Descriptor()
}

func (Job_Operation) Type() protoreflect.EnumType {
	return &file_configpb_config_proto_enumTypes[0]
}

func (x Job_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Job_Operation.Descriptor instead.
func (Job_Operation) EnumDescriptor() ([]byte, []int) {
	return file_configpb_config_proto_rawDescGZIP(), []int{1, 0}
}

// Config configures the iotcorelogger program.
type Config struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SupportedSensors []string               `protobuf:"bytes,3,rep,name=supported_sensors,json=supportedSensors,proto3" json:"supported_sensors,omitempty"`
	Jobs             []*Job                 `protobuf:"bytes,4,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_configpb_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_configpb_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_configpb_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetSupportedSensors() []string {
	if x != nil {
		return x.SupportedSensors
	}
	return nil
}

func (x *Config) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type Job struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cron spec that specifies when this job should run.
	Cronspec  string        `protobuf:"bytes,1,opt,name=cronspec,proto3" json:"cronspec,omitempty"`
	Operation Job_Operation `protobuf:"varint,2,opt,name=operation,proto3,enum=config.Job_Operation" json:"operation,omitempty"`
	// Sensors are processed in the order given.
	Sensors       []string `protobuf:"bytes,3,rep,name=sensors,proto3" json:"sensors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_configpb_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_configpb_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_configpb_config_proto_rawDescGZIP(), []int{1}
}

func (x *Job) GetCronspec() string {
	if x != nil {
		return x.Cronspec
	}
	return ""
}

func (x *Job) GetOperation() Job_Operation {
	if x != nil {
		return x.Operation
	}
	return Job_INVALID
}

func (x *Job) GetSensors() []string {
	if x != nil {
		return x.Sensors
	}
	return nil
}

var File_configpb_config_proto protoreflect.FileDescriptor

const file_configpb_config_proto_rawDesc = "" +
	"\n" +
	"\x15configpb/config.proto\x12\x06config\"b\n" +
	"\x06Config\x12+\n" +
	"\x11supported_sensors\x18\x03 \x03(\tR\x10supportedSensors\x12\x1f\n" +
	"\x04jobs\x18\x04 \x03(\v2\v.config.JobR\x04jobsJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03\"\xae\x01\n" +
	"\x03Job\x12\x1a\n" +
	"\bcronspec\x18\x01 \x01(\tR\bcronspec\x123\n" +
	"\toperation\x18\x02 \x01(\x0e2\x15.config.Job.OperationR\toperation\x12\x18\n" +
	"\asensors\x18\x03 \x03(\tR\asensors\"<\n" +
	"\tOperation\x12\v\n" +
	"\aINVALID\x10\x00\x12\t\n" +
	"\x05SETUP\x10\x01\x12\t\n" +
	"\x05SENSE\x10\x02\x12\f\n" +
	"\bSHUTDOWN\x10\x03B2Z0github.com/mtraver/environmental-sensor/configpbb\x06proto3"

var (
	file_configpb_config_proto_rawDescOnce sync.Once
	file_configpb_config_proto_rawDescData []byte
)

func file_configpb_config_proto_rawDescGZIP() []byte {
	file_configpb_config_proto_rawDescOnce.Do(func() {
		file_configpb_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configpb_config_proto_rawDesc), len(file_configpb_config_proto_rawDesc)))
	})
	return file_configpb_config_proto_rawDescData
}

var file_configpb_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_configpb_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_configpb_config_proto_goTypes = []any{
	(Job_Operation)(0), // 0: config.Job.Operation
	(*Config)(nil),     // 1: config.Config
	(*Job)(nil),        // 2: config.Job
}
var file_configpb_config_proto_depIdxs = []int32{
	2, // 0: config.Config.jobs:type_name -> config.Job
	0, // 1: config.Job.operation:type_name -> config.Job.Operation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_configpb_config_proto_init() }
func file_configpb_config_proto_init() {
	if File_configpb_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configpb_config_proto_rawDesc), len(file_configpb_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_configpb_config_proto_goTypes,
		DependencyIndexes: file_configpb_config_proto_depIdxs,
		EnumInfos:         file_configpb_config_proto_enumTypes,
		MessageInfos:      file_configpb_config_proto_msgTypes,
	}.Build()
	File_configpb_config_proto = out.File
	file_configpb_config_proto_goTypes = nil
	file_configpb_config_proto_depIdxs = nil
}
