// Code generated by "stringer -type=mode"; DO NOT EDIT.

package sen6x

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[modeUnknown-0]
	_ = x[modeIdle-1]
	_ = x[modeMeasurement-2]
}

const _mode_name = "modeUnknownmodeIdlemodeMeasurement"

var _mode_index = [...]uint8{0, 11, 19, 34}

func (i mode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_mode_index)-1 {
		return "mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _mode_name[_mode_index[idx]:_mode_index[idx+1]]
}
