# https://cloud.google.com/appengine/docs/standard/python/config/appref
runtime: go111

env_variables:
  IOTCORE_REGISTRY: 'TODO'

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
- url: /static
  static_dir: static
  secure: always
- url: /_ah/push-handlers/.*
  script: auto
  login: admin
  secure: always
- url: /.*
  script: auto
  secure: always
